# Numerical Python (NumPY)

In [1]:
!pip install numpy

Defaulting to user installation because normal site-packages is not writeable
Looking in links: /usr/share/pip-wheels


In [2]:
import numpy as np

## NumPy Arrays

### Types of arrays
- 1D array → vector
- 2D array → matrix
- ND array → tensor

NumPy stores data in homogeneous format (same data type).

### 1D Array

### Array Properties

- shape → structure of array
- ndim → number of dimensions
- size → total elements
- dtype → data type of elements
- reshape → Changing structure without changing data.

In [3]:
arr1 = np.array([1, 2, 3, 4, 5,6])

In [4]:
print("1D Array:\n", arr1)

1D Array:
 [1 2 3 4 5 6]


In [5]:
print("Shape:", arr1.shape)

Shape: (6,)


In [6]:
print("Dimensions:", arr1.ndim)

Dimensions: 1


In [7]:
print("Total Elements:", arr1.size)

Total Elements: 6


In [8]:
print("Data Type:", arr1.dtype)

Data Type: int64


In [9]:
new_arr = arr1.reshape(2, 3)
print(new_arr)

[[1 2 3]
 [4 5 6]]


### Vectorized Operations

NumPy allows element-wise operations without loops.
This is called vectorization → very fast computation.

In [10]:
print("Addition:\n", arr1 + 10)

Addition:
 [11 12 13 14 15 16]


In [11]:
print("Multiplication:\n", arr1 * 2)

Multiplication:
 [ 2  4  6  8 10 12]


In [12]:
print("Square:\n", arr1 ** 2)

Square:
 [ 1  4  9 16 25 36]


In [13]:
print("Division:\n", arr1 / 2)

Division:
 [0.5 1.  1.5 2.  2.5 3. ]


### Statistics in NumPy

- mean → average
- median → middle value
- std → data spread
- max → find maximum
- min → find minimum

In [14]:
print("Mean (Average): ", np.mean(arr1))

Mean (Average):  3.5


In [15]:
print("Median (Middle Value): ", np.median(arr1))

Median (Middle Value):  3.5


In [16]:
print("Minimum: ", np.min(arr1))  

Minimum:  1


In [17]:
print("Maximum: ", np.max(arr1)) 

Maximum:  6


In [18]:
print("Standard Deviation: ", np.std(arr1))   

Standard Deviation:  1.707825127659933


### Indexing & Slicing

- Indexing → accessing single value
- Slicing → accessing range of values
- View(Slice) -> Change Original Array
- Copy(Array) -> Doesn't Change Original Array

In [19]:
print("Element at index 0:", arr1[0])

Element at index 0: 1


In [20]:
print("Element at index 3:", arr1[3])

Element at index 3: 4


In [21]:
print("Last element:", arr1[-1])

Last element: 6


In [22]:
print("Slice [1:4]:", arr1[1:4])

Slice [1:4]: [2 3 4]


In [23]:
print("Every 2nd element:", arr1[::2])

Every 2nd element: [1 3 5]


In [24]:
# VIEW (slicing)
arr1=np.array([1,2,3,4,5])
print("Before changing:", arr1)
slice_arr = arr1[1:4]
slice_arr[0] = 999   # changes original
print("After changing:", arr1)
print("Slice:", slice_arr)

Before changing: [1 2 3 4 5]
After changing: [  1 999   3   4   5]
Slice: [999   3   4]


In [25]:
# COPY
arr1=np.array([1,2,3,4,5])
print("Before changing:", arr1)
copy_arr = arr1.copy()
copy_arr[0] = 555
print("After changing:", arr1)
print("Copy:", copy_arr)

Before changing: [1 2 3 4 5]
After changing: [1 2 3 4 5]
Copy: [555   2   3   4   5]
