# Numerical Python (NumPY) 2D Array

In [1]:
!pip install numpy

Defaulting to user installation because normal site-packages is not writeable
Looking in links: /usr/share/pip-wheels


In [2]:
import numpy as np

## NumPy Arrays

### Types of arrays
- 1D array → vector
- 2D array → matrix
- ND array → tensor

NumPy stores data in homogeneous format (same data type).

### 2D Array

### Array Properties

- shape → structure of array
- ndim → number of dimensions
- size → total elements
- dtype → data type of elements
- reshape → Changing structure without changing data.

In [ ]:
arr2 = np.array([[1, 2, 3],
                 [4, 5, 6]])

In [ ]:
print("2D Array:\n", arr2)

In [ ]:
print("Shape (rows, columns):", arr2.shape)

In [ ]:
print("Dimensions:", arr2.ndim)

In [ ]:
print("Total Elements:", arr2.size)

In [ ]:
print("Data Type:", arr2.dtype)

2D Array:
 [[1 2 3]
 [4 5 6]]
Shape (rows, columns): (2, 3)
Dimensions: 2
Total Elements: 6
Data Type: int64


In [11]:
new_arr = arr2.reshape(3,2)
print(new_arr)

[[1 2]
 [3 4]
 [5 6]]


### Vectorized Operations

NumPy allows element-wise operations without loops.
This is called vectorization → very fast computation.

In [ ]:
print("Addition:\n", arr2 + 10)

In [ ]:
print("Multiplication:\n", arr2 * 2)

In [ ]:
print("Square:\n", arr2 ** 2)

In [ ]:
print("Division:\n", arr2 / 2)

Addition:
 [[11 12 13]
 [14 15 16]]
Multiplication:
 [[ 2  4  6]
 [ 8 10 12]]
Square:
 [[ 1  4  9]
 [16 25 36]]
Division:
 [[0.5 1.  1.5]
 [2.  2.5 3. ]]


### Statistics in NumPy

- mean → average
- median → middle value
- std → data spread
- max → find maximum
- min → find minimum

In [ ]:
print("Mean (Average): ", np.mean(arr2))

In [ ]:
print("Median (Middle Value): ", np.median(arr2))

In [ ]:
print("Minimum: ", np.min(arr2))  

In [ ]:
print("Maximum: ", np.max(arr2)) 

In [ ]:
print("Standard Deviation: ", np.std(arr2))   

Mean (Average):  3.5
Median (Middle Value):  3.5
Minimum:  1
Maximum:  6
Standard Deviation:  1.707825127659933


### Indexing & Slicing

- Indexing → accessing single value
- Slicing → accessing range of values
- View(Slice) -> Change Original Array
- Copy(Array) -> Doesn't Change Original Array

In [ ]:
print("Element [0,1] (row0,col1):", arr2[0, 1])

In [ ]:
print("Element [1,2] (row1,col2):", arr2[1, 2])

In [ ]:
print("Negative Index [-1,-2]:", arr2[-1, -2])   # last row, 2nd last col

In [ ]:
print("Negative Index [-2,-1]:", arr2[-2, -1])   # 1st row, last col

In [ ]:
print("Slice rows 0-1, cols 1-2:\n", arr2[0:2, 1:3])

In [ ]:
print("Every 2nd row & col:\n", arr2[::2, ::2])

Element [0,1] (row0,col1): 2
Element [1,2] (row1,col2): 6
Negative Index [-1,-2]: 5
Negative Index [-2,-1]: 3
Slice rows 0-1, cols 1-2:
 [[2 3]
 [5 6]]
Every 2nd row & col:
 [[1 3]]


In [15]:
# VIEW (slicing)
arr2 = np.array([
    [1, 2, 3],
    [4, 5, 6]
])
print("Before changing:\n", arr2)
slice_arr = arr2[0, :2]
slice_arr[0] = 999   # changes original
print("After changing:\n", arr2)
print("Slice:", slice_arr)

Before changing:
 [[1 2 3]
 [4 5 6]]
After changing:
 [[999   2   3]
 [  4   5   6]]
Slice: [999   2]


In [16]:
# COPY
arr2 = np.array([
    [1, 2, 3],
    [4, 5, 6]
])
print("Before changing:\n", arr2)
copy_arr = arr2.copy()
copy_arr[0,0] = 555
print("After changing:\n", arr2)
print("Copy:\n", copy_arr)

Before changing:
 [[1 2 3]
 [4 5 6]]
After changing:
 [[1 2 3]
 [4 5 6]]
Copy:
 [[555   2   3]
 [  4   5   6]]
