# Numerical Python (NumPY) 3D Array

In [1]:
!pip install numpy

Defaulting to user installation because normal site-packages is not writeable
Looking in links: /usr/share/pip-wheels


In [2]:
import numpy as np

## NumPy Arrays

### Types of arrays
- 1D array → vector
- 2D array → matrix
- ND array → tensor

NumPy stores data in homogeneous format (same data type).

### 3D Array

### Array Properties

- shape → structure of array
- ndim → number of dimensions
- size → total elements
- dtype → data type of elements
- reshape → Changing structure without changing data.

In [3]:
arr3 = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])

In [4]:
print("3D Array:\n", arr3)

3D Array:
 [[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]


In [5]:
print("Shape (layers, rows, columns):", arr3.shape)

Shape (layers, rows, columns): (2, 2, 3)


In [6]:
print("Dimensions:", arr3.ndim)

Dimensions: 3


In [7]:
print("Total Elements:", arr3.size)

Total Elements: 12


In [8]:
print("Data Type:", arr3.dtype)

Data Type: int64


In [9]:
new_arr = arr3.reshape(6,2)
print(new_arr)

[[ 1  2]
 [ 3  4]
 [ 5  6]
 [ 7  8]
 [ 9 10]
 [11 12]]


### Vectorized Operations

NumPy allows element-wise operations without loops.
This is called vectorization → very fast computation.

In [10]:
print("Addition:\n", arr3 + 10)

Addition:
 [[[11 12 13]
  [14 15 16]]

 [[17 18 19]
  [20 21 22]]]


In [11]:
print("Multiplication:\n", arr3 * 2)

Multiplication:
 [[[ 2  4  6]
  [ 8 10 12]]

 [[14 16 18]
  [20 22 24]]]


In [12]:
print("Square:\n", arr3 ** 2)

Square:
 [[[  1   4   9]
  [ 16  25  36]]

 [[ 49  64  81]
  [100 121 144]]]


In [13]:
print("Division:\n", arr3 / 2)

Division:
 [[[0.5 1.  1.5]
  [2.  2.5 3. ]]

 [[3.5 4.  4.5]
  [5.  5.5 6. ]]]


### Statistics in NumPy

- mean → average
- median → middle value
- std → data spread
- max → find maximum
- min → find minimum

In [14]:
print("Mean (Average): ", np.mean(arr3))

Mean (Average):  6.5


In [15]:
print("Median (Middle Value): ", np.median(arr3))

Median (Middle Value):  6.5


In [16]:
print("Minimum: ", np.min(arr3))  

Minimum:  1


In [17]:
print("Maximum: ", np.max(arr3)) 

Maximum:  12


In [18]:
print("Standard Deviation: ", np.std(arr3))   

Standard Deviation:  3.452052529534663


### Indexing & Slicing

- Indexing → accessing single value
- Slicing → accessing range of values
- View(Slice) -> Change Original Array
- Copy(Array) -> Doesn't Change Original Array

In [19]:
print("Element [0,1,2] (layer0,row1,col2):", arr3[0, 1, 2])

Element [0,1,2] (layer0,row1,col2): 6


In [20]:
print("Element [1,0,1] (layer1,row0,col1):", arr3[1, 0, 1])

Element [1,0,1] (layer1,row0,col1): 8


In [21]:
print("Last layer last row last col:", arr3[-1, -1, -1])

Last layer last row last col: 12


In [22]:
print("Slice (all layers, row 0-1, col 1-2):\n", arr3[:, 0:2, 1:3])

Slice (all layers, row 0-1, col 1-2):
 [[[ 2  3]
  [ 5  6]]

 [[ 8  9]
  [11 12]]]


In [23]:
print("Every 2nd element in layers/rows/cols:\n", arr3[::1, ::2, ::2])

Every 2nd element in layers/rows/cols:
 [[[1 3]]

 [[7 9]]]


In [24]:
# VIEW (slicing)
arr3 = np.array([
    [[1, 2, 3], [4, 5, 6]],
    [[7, 8, 9], [10, 11, 12]]
])
print("Before changing:\n", arr3)
slice_arr = arr3[0, :, :]
slice_arr[0, 0] = 999   # changes original
print("After changing:\n", arr3)
print("Slice:\n", slice_arr)

Before changing:
 [[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]
After changing:
 [[[999   2   3]
  [  4   5   6]]

 [[  7   8   9]
  [ 10  11  12]]]
Slice:
 [[999   2   3]
 [  4   5   6]]


In [25]:
# COPY
arr3 = np.array([
    [[1, 2, 3], [4, 5, 6]],
    [[7, 8, 9], [10, 11, 12]]
])
print("Before changing:\n", arr3)
copy_arr = arr3.copy()
copy_arr[0, 0, 0] = 555
print("After changing:\n", arr3)
print("Copy:\n", copy_arr)

Before changing:
 [[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]
After changing:
 [[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]
Copy:
 [[[555   2   3]
  [  4   5   6]]

 [[  7   8   9]
  [ 10  11  12]]]
