In [1]:
import numpy as np

# NumPy Functions

- zeros() → array of 0s
- ones() → array of 1s
- full() → array filled with value
- arange() → range with step
- linspace() → equal spaced values
- eye() → identity matrix
- diag() → diagonal matrix / diagonal extract
- dtype → data type check
- astype() → change data type

In [2]:
print(np.zeros((2,3)))

[[0. 0. 0.]
 [0. 0. 0.]]


In [3]:
print(np.ones((2,3)))

[[1. 1. 1.]
 [1. 1. 1.]]


In [4]:
print(np.full((2,3),7))  #full(size,number)

[[7 7 7]
 [7 7 7]]


In [5]:
print(np.arange(0,10,2)) #arange(start,end-1,steps)

[0 2 4 6 8]


In [6]:
print(np.linspace(0,1,5))  #linspace(start,end,complete in steps)

[0.   0.25 0.5  0.75 1.  ]


In [7]:
print(np.eye(3))         #identity matrix

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [8]:
print(np.diag([1,2,3]))

[[1 0 0]
 [0 2 0]
 [0 0 3]]


In [9]:
print(np.array([1,2,3],dtype=float))

[1. 2. 3.]


In [10]:
print(np.array([1.5,2.7,3.9]).astype(int))

[1 2 3]


# Random module

In [11]:
print(np.random.rand(3))      # random values (0–1)

[0.9932585  0.24677894 0.68766343]


In [12]:
print(np.random.randint(1,10)) # random integer

4


In [13]:
print(np.random.randn(3,3))   # normal distribution

[[-0.82708875 -1.13318141 -0.58910335]
 [-0.55862001  1.27702771  0.78968303]
 [ 1.74060471 -0.38039429 -0.83373903]]
