# Numerical Python (NumPY)

In [1]:
!pip install numpy

Defaulting to user installation because normal site-packages is not writeable
Looking in links: /usr/share/pip-wheels


In [2]:
import numpy as np

## NumPy Arrays

### Types of arrays
- 1D array → vector
- 2D array → matrix
- ND array → tensor

NumPy stores data in homogeneous format (same data type).

### Array Properties

- shape → structure of array
- ndim → number of dimensions
- size → total elements
- dtype → data type of elements
- reshape → Changing structure without changing data.

### Vectorized Operations

NumPy allows element-wise operations without loops.
This is called vectorization → very fast computation.

### Statistics in NumPy

- mean → average
- median → middle value
- std → data spread
- max → find maximum
- min → find minimum

### Indexing & Slicing

- Indexing → accessing single value
- Slicing → accessing range of values
- View(Slice) -> Change Original Array
- Copy(Array) -> Doesn't Change Original Array

### 1D Array

In [3]:
import numpy as np

arr1 = np.array([1, 2, 3, 4, 5,6])
print("1D Array:\n", arr1)
print("Shape:", arr1.shape)
print("Dimensions:", arr1.ndim)
print("Total Elements:", arr1.size)
print("Data Type:", arr1.dtype)

1D Array:
 [1 2 3 4 5 6]
Shape: (6,)
Dimensions: 1
Total Elements: 6
Data Type: int64


In [4]:
new_arr = arr1.reshape(2, 3)
print(new_arr)

[[1 2 3]
 [4 5 6]]


In [5]:
print("Addition:\n", arr1 + 10)
print("Multiplication:\n", arr1 * 2)
print("Square:\n", arr1 ** 2)
print("Division:\n", arr1 / 2)

Addition:
 [11 12 13 14 15 16]
Multiplication:
 [ 2  4  6  8 10 12]
Square:
 [ 1  4  9 16 25 36]
Division:
 [0.5 1.  1.5 2.  2.5 3. ]


In [6]:
print("Mean (Average): ", np.mean(arr1))
print("Median (Middle Value): ", np.median(arr1))
print("Minimum: ", np.min(arr1))  
print("Maximum: ", np.max(arr1)) 
print("Standard Deviation: ", np.std(arr1))   

Mean (Average):  3.5
Median (Middle Value):  3.5
Minimum:  1
Maximum:  6
Standard Deviation:  1.707825127659933


In [7]:
print("Element at index 0:", arr1[0])
print("Element at index 3:", arr1[3])
print("Last element:", arr1[-1])
print("Slice [1:4]:", arr1[1:4])
print("Every 2nd element:", arr1[::2])

Element at index 0: 1
Element at index 3: 4
Last element: 6
Slice [1:4]: [2 3 4]
Every 2nd element: [1 3 5]


In [8]:
# VIEW (slicing)
arr1=np.array([1,2,3,4,5])
print("Before changing:", arr1)
slice_arr = arr1[1:4]
slice_arr[0] = 999   # changes original
print("After changing:", arr1)
print("Slice:", slice_arr)

Before changing: [1 2 3 4 5]
After changing: [  1 999   3   4   5]
Slice: [999   3   4]


In [9]:
# COPY
arr1=np.array([1,2,3,4,5])
print("Before changing:", arr1)
copy_arr = arr1.copy()
copy_arr[0] = 555
print("After changing:", arr1)
print("Copy:", copy_arr)

Before changing: [1 2 3 4 5]
After changing: [1 2 3 4 5]
Copy: [555   2   3   4   5]


### 2D Array

In [10]:
arr2 = np.array([[1, 2, 3],
                 [4, 5, 6]])
print("2D Array:\n", arr2)
print("Shape (rows, columns):", arr2.shape)
print("Dimensions:", arr2.ndim)
print("Total Elements:", arr2.size)
print("Data Type:", arr2.dtype)

2D Array:
 [[1 2 3]
 [4 5 6]]
Shape (rows, columns): (2, 3)
Dimensions: 2
Total Elements: 6
Data Type: int64


In [11]:
new_arr = arr2.reshape(3,2)
print(new_arr)

[[1 2]
 [3 4]
 [5 6]]


In [12]:
print("Addition:\n", arr2 + 10)
print("Multiplication:\n", arr2 * 2)
print("Square:\n", arr2 ** 2)
print("Division:\n", arr2 / 2)

Addition:
 [[11 12 13]
 [14 15 16]]
Multiplication:
 [[ 2  4  6]
 [ 8 10 12]]
Square:
 [[ 1  4  9]
 [16 25 36]]
Division:
 [[0.5 1.  1.5]
 [2.  2.5 3. ]]


In [13]:
print("Mean (Average): ", np.mean(arr2))
print("Median (Middle Value): ", np.median(arr2))
print("Minimum: ", np.min(arr2))  
print("Maximum: ", np.max(arr2)) 
print("Standard Deviation: ", np.std(arr2))   

Mean (Average):  3.5
Median (Middle Value):  3.5
Minimum:  1
Maximum:  6
Standard Deviation:  1.707825127659933


In [14]:
print("Element [0,1] (row0,col1):", arr2[0, 1])
print("Element [1,2] (row1,col2):", arr2[1, 2])
print("Negative Index [-1,-2]:", arr2[-1, -2])   # last row, 2nd last col
print("Negative Index [-2,-1]:", arr2[-2, -1])   # 1st row, last col
print("Slice rows 0-1, cols 1-2:\n", arr2[0:2, 1:3])
print("Every 2nd row & col:\n", arr2[::2, ::2])

Element [0,1] (row0,col1): 2
Element [1,2] (row1,col2): 6
Negative Index [-1,-2]: 5
Negative Index [-2,-1]: 3
Slice rows 0-1, cols 1-2:
 [[2 3]
 [5 6]]
Every 2nd row & col:
 [[1 3]]


In [15]:
# VIEW (slicing)
arr2 = np.array([
    [1, 2, 3],
    [4, 5, 6]
])
print("Before changing:\n", arr2)
slice_arr = arr2[0, :2]
slice_arr[0] = 999   # changes original
print("After changing:\n", arr2)
print("Slice:", slice_arr)

Before changing:
 [[1 2 3]
 [4 5 6]]
After changing:
 [[999   2   3]
 [  4   5   6]]
Slice: [999   2]


In [16]:
# COPY
arr2 = np.array([
    [1, 2, 3],
    [4, 5, 6]
])
print("Before changing:\n", arr2)
copy_arr = arr2.copy()
copy_arr[0,0] = 555
print("After changing:\n", arr2)
print("Copy:\n", copy_arr)

Before changing:
 [[1 2 3]
 [4 5 6]]
After changing:
 [[1 2 3]
 [4 5 6]]
Copy:
 [[555   2   3]
 [  4   5   6]]


### 3D Array

In [17]:
arr3 = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])
print("3D Array:\n", arr3)
print("Shape (layers, rows, columns):", arr3.shape)
print("Dimensions:", arr3.ndim)
print("Total Elements:", arr3.size)
print("Data Type:", arr3.dtype)

3D Array:
 [[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]
Shape (layers, rows, columns): (2, 2, 3)
Dimensions: 3
Total Elements: 12
Data Type: int64


In [18]:
new_arr = arr3.reshape(6,2)
print(new_arr)

[[ 1  2]
 [ 3  4]
 [ 5  6]
 [ 7  8]
 [ 9 10]
 [11 12]]


In [19]:
print("Addition:\n", arr3 + 10)
print("Multiplication:\n", arr3 * 2)
print("Square:\n", arr3 ** 2)
print("Division:\n", arr3 / 2)

Addition:
 [[[11 12 13]
  [14 15 16]]

 [[17 18 19]
  [20 21 22]]]
Multiplication:
 [[[ 2  4  6]
  [ 8 10 12]]

 [[14 16 18]
  [20 22 24]]]
Square:
 [[[  1   4   9]
  [ 16  25  36]]

 [[ 49  64  81]
  [100 121 144]]]
Division:
 [[[0.5 1.  1.5]
  [2.  2.5 3. ]]

 [[3.5 4.  4.5]
  [5.  5.5 6. ]]]


In [20]:
print("Mean (Average): ", np.mean(arr3))
print("Median (Middle Value): ", np.median(arr3))
print("Minimum: ", np.min(arr3))  
print("Maximum: ", np.max(arr3)) 
print("Standard Deviation: ", np.std(arr3))   

Mean (Average):  6.5
Median (Middle Value):  6.5
Minimum:  1
Maximum:  12
Standard Deviation:  3.452052529534663


In [21]:
print("Element [0,1,2] (layer0,row1,col2):", arr3[0, 1, 2])
print("Element [1,0,1] (layer1,row0,col1):", arr3[1, 0, 1])
print("Last layer last row last col:", arr3[-1, -1, -1])
print("Slice (all layers, row 0-1, col 1-2):\n", arr3[:, 0:2, 1:3])
print("Every 2nd element in layers/rows/cols:\n", arr3[::1, ::2, ::2])

Element [0,1,2] (layer0,row1,col2): 6
Element [1,0,1] (layer1,row0,col1): 8
Last layer last row last col: 12
Slice (all layers, row 0-1, col 1-2):
 [[[ 2  3]
  [ 5  6]]

 [[ 8  9]
  [11 12]]]
Every 2nd element in layers/rows/cols:
 [[[1 3]]

 [[7 9]]]


In [22]:
# VIEW (slicing)
arr3 = np.array([
    [[1, 2, 3], [4, 5, 6]],
    [[7, 8, 9], [10, 11, 12]]
])
print("Before changing:\n", arr3)
slice_arr = arr3[0, :, :]
slice_arr[0, 0] = 999   # changes original
print("After changing:\n", arr3)
print("Slice:\n", slice_arr)

Before changing:
 [[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]
After changing:
 [[[999   2   3]
  [  4   5   6]]

 [[  7   8   9]
  [ 10  11  12]]]
Slice:
 [[999   2   3]
 [  4   5   6]]


In [23]:
# COPY
arr3 = np.array([
    [[1, 2, 3], [4, 5, 6]],
    [[7, 8, 9], [10, 11, 12]]
])
print("Before changing:\n", arr3)
copy_arr = arr3.copy()
copy_arr[0, 0, 0] = 555
print("After changing:\n", arr3)
print("Copy:\n", copy_arr)

Before changing:
 [[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]
After changing:
 [[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]
Copy:
 [[[555   2   3]
  [  4   5   6]]

 [[  7   8   9]
  [ 10  11  12]]]


# NumPy Functions (Short Notes)

- zeros() → array of 0s
- ones() → array of 1s
- full() → array filled with value
- arange() → range with step
- linspace() → equal spaced values
- eye() → identity matrix
- diag() → diagonal matrix / diagonal extract
- dtype → data type check
- astype() → change data type

In [24]:
print(np.zeros((2,3)))

[[0. 0. 0.]
 [0. 0. 0.]]


In [25]:
print(np.ones((2,3)))

[[1. 1. 1.]
 [1. 1. 1.]]


In [26]:
print(np.full((2,3),7))  #full(size,number)

[[7 7 7]
 [7 7 7]]


In [27]:
print(np.arange(0,10,2)) #arange(start,end-1,steps)

[0 2 4 6 8]


In [28]:
print(np.linspace(0,1,5))  #linspace(start,end,complete in steps)

[0.   0.25 0.5  0.75 1.  ]


In [29]:
print(np.eye(3))         #identity matrix

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [30]:
print(np.diag([1,2,3]))

[[1 0 0]
 [0 2 0]
 [0 0 3]]


In [31]:
print(np.array([1,2,3],dtype=float))

[1. 2. 3.]


In [32]:
print(np.array([1.5,2.7,3.9]).astype(int))

[1 2 3]


# Random module

In [33]:
print(np.random.rand(3))      # random values (0–1)

[0.85728603 0.66356185 0.06145055]


In [34]:
print(np.random.randint(1,10)) # random integer

9


In [35]:
print(np.random.randn(3,3))   # normal distribution

[[-1.44822857 -2.10971794 -0.24293508]
 [-0.32267449  0.30673869 -0.78846816]
 [ 1.22436735  0.04268618  0.17886154]]


# Coin Flip Probability Simulation using NumPy

This example simulates **100,000 coin flips** using NumPy random functions.

The program estimates:
- Probability of Heads
- Probability of Tails

A coin has:
- `1` → Heads
- `0` → Tails

In [36]:
# simulate 100k coin flips
rng=np.random.default_rng()
flips=rng.integers(0,2,size=100000)
prob_heads=np.mean(flips)
prob_tails=1-prob_heads
print("Estimated probability of heads: ", prob_heads)
print("Estimated probability of tails: ", prob_tails)
print("Total: ", prob_heads+prob_tails)

Estimated probability of heads:  0.49681
Estimated probability of tails:  0.50319
Total:  1.0


#### Seed to stablility

In [37]:
# simulate 100k coin flips with fixed seed
rng=np.random.default_rng(seed=42)
flips=rng.integers(0,2,size=100000)
prob_heads=np.mean(flips)
prob_tails=1-prob_heads
print("Estimated probability of heads: ", prob_heads)
print("Estimated probability of tails: ", prob_tails)
print("Total: ", prob_heads+prob_tails)

Estimated probability of heads:  0.50089
Estimated probability of tails:  0.49911000000000005
Total:  1.0


# Python List vs NumPy Array Performance

This example compares the execution speed of:

- Normal Python Lists
- NumPy Arrays

The goal is to show why NumPy is faster for numerical computations.


In [38]:
import time 

py_list=list(range(1_000_000))
py_result=[]
start_time=time.time()
for i in py_list:
    py_result.append(i+5)
end_time=time.time()
print("Python List Time: ", end_time - start_time)

np_array=np.arange(1_000_000)
start_time=time.time()
np_result=np_array+5
end_time=time.time()
print("Numpy Array Time: ", end_time - start_time)

Python List Time:  0.10406208038330078
Numpy Array Time:  0.01801466941833496
